#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aWFS210.Resource", IsApplication=true)]

namespace aWFS210
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int MarkerMeasurements = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Measurements = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black_overlay = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int light_grey = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int transparent = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundcalibrating = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backgroundmeasurements = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backgroundsurfaceview = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int battcharging1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int battcharging2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int battcharging3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int batteryanimation = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int battfull = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int battlow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btncyan = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btngreen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btngrey = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btnred = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btnwhite = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btnyellow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int buttoncyan = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int buttongreen = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int buttonred = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int buttonsettings = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int buttonwhite = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int buttonyellow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int charger = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int down = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fallingbackground = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int measurementstyle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ninefalling = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ninefallingpressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ninegreen = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ninerising = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ninerisingpressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ninetimebaseright = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int seperatorhorizontal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int seperatorvertical = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int shape_blank = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int slopedownselected = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int slopedownunselected = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int slopeupselected = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int slopeupunselected = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int spinner = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int spinnerbg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int splahlogo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int timebaseleft = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int timebaseleftdisabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int timebaseright = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int timebaserightdisabled = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int toettoet = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int uppressed = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int voltdown1 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int voltdown2 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int voltdowndisabled = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int voltup1 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int voltup2 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int voltupdisabled = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int wifiicon = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070044
			public const int ScopeView = 2131165252;
			
			// aapt resource value: 0x7f070006
			public const int btnAC1 = 2131165190;
			
			// aapt resource value: 0x7f07001f
			public const int btnAC2 = 2131165215;
			
			// aapt resource value: 0x7f070041
			public const int btnAutoRange = 2131165249;
			
			// aapt resource value: 0x7f070002
			public const int btnCH1 = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public const int btnCH2 = 2131165211;
			
			// aapt resource value: 0x7f070007
			public const int btnDC1 = 2131165191;
			
			// aapt resource value: 0x7f070020
			public const int btnDC2 = 2131165216;
			
			// aapt resource value: 0x7f070037
			public const int btnFalling = 2131165239;
			
			// aapt resource value: 0x7f070008
			public const int btnGND1 = 2131165192;
			
			// aapt resource value: 0x7f070021
			public const int btnGND2 = 2131165217;
			
			// aapt resource value: 0x7f07003a
			public const int btnHold = 2131165242;
			
			// aapt resource value: 0x7f070039
			public const int btnNormal = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int btnOnce = 2131165243;
			
			// aapt resource value: 0x7f07000a
			public const int btnPROBE1 = 2131165194;
			
			// aapt resource value: 0x7f070023
			public const int btnPROBE2 = 2131165219;
			
			// aapt resource value: 0x7f070036
			public const int btnRising = 2131165238;
			
			// aapt resource value: 0x7f070038
			public const int btnRun = 2131165240;
			
			// aapt resource value: 0x7f070030
			public const int btnSettings = 2131165232;
			
			// aapt resource value: 0x7f07003e
			public const int btnTimeBaseLeft = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int btnTimeBaseRight = 2131165247;
			
			// aapt resource value: 0x7f070034
			public const int btnTriggerCh1 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int btnTriggerCh2 = 2131165237;
			
			// aapt resource value: 0x7f07000c
			public const int btnVoltDown1 = 2131165196;
			
			// aapt resource value: 0x7f070025
			public const int btnVoltDown2 = 2131165221;
			
			// aapt resource value: 0x7f07000e
			public const int btnVoltUp1 = 2131165198;
			
			// aapt resource value: 0x7f070027
			public const int btnVoltUp2 = 2131165223;
			
			// aapt resource value: 0x7f070011
			public const int fakeMarkerButton1 = 2131165201;
			
			// aapt resource value: 0x7f07002a
			public const int fakeMarkerButton2 = 2131165226;
			
			// aapt resource value: 0x7f070015
			public const int fakebutton1 = 2131165205;
			
			// aapt resource value: 0x7f07002e
			public const int fakebutton2 = 2131165230;
			
			// aapt resource value: 0x7f070043
			public const int helperrelativelayout = 2131165251;
			
			// aapt resource value: 0x7f070018
			public const int imgbatteryindicator = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int llCH1 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int llCH1helper = 2131165185;
			
			// aapt resource value: 0x7f07001d
			public const int llCH2 = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int llCH2helper = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int rlActivity = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int rlHelperMarkerMeasurement1 = 2131165199;
			
			// aapt resource value: 0x7f070028
			public const int rlHelperMarkerMeasurement2 = 2131165224;
			
			// aapt resource value: 0x7f070013
			public const int rlHelperMeasurement1 = 2131165203;
			
			// aapt resource value: 0x7f07002c
			public const int rlHelperMeasurement2 = 2131165228;
			
			// aapt resource value: 0x7f070017
			public const int rlbattery = 2131165207;
			
			// aapt resource value: 0x7f07001e
			public const int rlsettings = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int rltriggerlayout = 2131165210;
			
			// aapt resource value: 0x7f070003
			public const int seperatorV1 = 2131165187;
			
			// aapt resource value: 0x7f070040
			public const int seperatorV10 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int seperatorV11 = 2131165250;
			
			// aapt resource value: 0x7f070005
			public const int seperatorV12 = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int seperatorV2 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int seperatorV3 = 2131165195;
			
			// aapt resource value: 0x7f070032
			public const int seperatorV4 = 2131165234;
			
			// aapt resource value: 0x7f07003c
			public const int seperatorV5 = 2131165244;
			
			// aapt resource value: 0x7f070031
			public const int seperatorV6 = 2131165233;
			
			// aapt resource value: 0x7f070022
			public const int seperatorV7 = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int seperatorV8 = 2131165220;
			
			// aapt resource value: 0x7f07001c
			public const int seperatorV9 = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int spMarkerMeasurement1 = 2131165202;
			
			// aapt resource value: 0x7f07002b
			public const int spMarkerMeasurement2 = 2131165227;
			
			// aapt resource value: 0x7f070016
			public const int spMeasurement1 = 2131165206;
			
			// aapt resource value: 0x7f07002f
			public const int spMeasurement2 = 2131165231;
			
			// aapt resource value: 0x7f070010
			public const int txtMarkerMeasurement1 = 2131165200;
			
			// aapt resource value: 0x7f070029
			public const int txtMarkerMeasurement2 = 2131165225;
			
			// aapt resource value: 0x7f070014
			public const int txtMeasurement1 = 2131165204;
			
			// aapt resource value: 0x7f07002d
			public const int txtMeasurement2 = 2131165229;
			
			// aapt resource value: 0x7f07003d
			public const int txtTimebase = 2131165245;
			
			// aapt resource value: 0x7f070033
			public const int txtTrigger = 2131165235;
			
			// aapt resource value: 0x7f07000d
			public const int txtVDIV1 = 2131165197;
			
			// aapt resource value: 0x7f070026
			public const int txtVDIV2 = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int AC = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ACbold = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int DC = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int DCbold = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int GND = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int GNDbold = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int autorange = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int battery = 2131034137;
			
			// aapt resource value: 0x7f050001
			public const int channel1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int channel1bold = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int channel1boldfull = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int channel1full = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int channel2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int channel2bold = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int channel2boldfull = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int channel2full = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int hold = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int holdbold = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int normal = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int normalbold = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int once = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int oncebold = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int placeholder = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int probe = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int run = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int runbold = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int seperator = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int timebase = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int trigger = 2131034139;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
