#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WFS210.Droid.Resource", IsApplication=true)]

namespace WFS210.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int MarkerMeasurements = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Measurements = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black_overlay = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int light_grey = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int transparent = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundcalibrating = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backgroundmeasurements = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backgroundsurfaceview = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int battcharging1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int battcharging2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int battcharging3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int batteryanimation = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int battfull = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int battlow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btncyan = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btngreen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btngrey = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btnred = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btnwhite = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btnyellow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int buttoncyan = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int buttongreen = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int buttonred = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int buttonsettings = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int buttonwhite = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int buttonyellow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int charger = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int down = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fallingbackground = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int marker1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int marker2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int markera = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int markerb = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int markertriggerdown = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int markertriggerup = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int measurementstyle = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ninefalling = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ninefallingpressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ninegreen = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ninerising = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ninerisingpressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ninetimebaseright = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int seperatorhorizontal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int seperatorvertical = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int shape_blank = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int slopedownselected = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int slopedownunselected = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int slopeupselected = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int slopeupunselected = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int spinner = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int spinnerbg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int splahlogo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int timebaseleft = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int timebaseleftdisabled = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int timebaseright = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int timebaserightdisabled = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int toettoet = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int uppressed = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int voltdown1 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int voltdown2 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int voltdowndisabled = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int voltup1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int voltup2 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int voltupdisabled = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int vti_bg = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int wifiicon = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int zeroline1 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int zeroline2 = 2130837570;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080044
			public const int CalibratingIndicator = 2131230788;
			
			// aapt resource value: 0x7f080042
			public const int SignalView = 2131230786;
			
			// aapt resource value: 0x7f080043
			public const int VoltTimeIndicator = 2131230787;
			
			// aapt resource value: 0x7f080006
			public const int btnAC1 = 2131230726;
			
			// aapt resource value: 0x7f08001f
			public const int btnAC2 = 2131230751;
			
			// aapt resource value: 0x7f080040
			public const int btnAutoRange = 2131230784;
			
			// aapt resource value: 0x7f080002
			public const int btnCH1 = 2131230722;
			
			// aapt resource value: 0x7f08001b
			public const int btnCH2 = 2131230747;
			
			// aapt resource value: 0x7f080007
			public const int btnDC1 = 2131230727;
			
			// aapt resource value: 0x7f080020
			public const int btnDC2 = 2131230752;
			
			// aapt resource value: 0x7f080036
			public const int btnFalling = 2131230774;
			
			// aapt resource value: 0x7f080008
			public const int btnGND1 = 2131230728;
			
			// aapt resource value: 0x7f080021
			public const int btnGND2 = 2131230753;
			
			// aapt resource value: 0x7f080039
			public const int btnHold = 2131230777;
			
			// aapt resource value: 0x7f080038
			public const int btnNormal = 2131230776;
			
			// aapt resource value: 0x7f08003a
			public const int btnOnce = 2131230778;
			
			// aapt resource value: 0x7f08000a
			public const int btnPROBE1 = 2131230730;
			
			// aapt resource value: 0x7f080023
			public const int btnPROBE2 = 2131230755;
			
			// aapt resource value: 0x7f080035
			public const int btnRising = 2131230773;
			
			// aapt resource value: 0x7f080037
			public const int btnRun = 2131230775;
			
			// aapt resource value: 0x7f080030
			public const int btnSettings = 2131230768;
			
			// aapt resource value: 0x7f08003d
			public const int btnTimeBaseLeft = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int btnTimeBaseRight = 2131230782;
			
			// aapt resource value: 0x7f080033
			public const int btnTriggerCh1 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int btnTriggerCh2 = 2131230772;
			
			// aapt resource value: 0x7f08000c
			public const int btnVoltDown1 = 2131230732;
			
			// aapt resource value: 0x7f080025
			public const int btnVoltDown2 = 2131230757;
			
			// aapt resource value: 0x7f08000e
			public const int btnVoltUp1 = 2131230734;
			
			// aapt resource value: 0x7f080027
			public const int btnVoltUp2 = 2131230759;
			
			// aapt resource value: 0x7f080011
			public const int fakeMarkerButton1 = 2131230737;
			
			// aapt resource value: 0x7f08002a
			public const int fakeMarkerButton2 = 2131230762;
			
			// aapt resource value: 0x7f080015
			public const int fakebutton1 = 2131230741;
			
			// aapt resource value: 0x7f08002e
			public const int fakebutton2 = 2131230766;
			
			// aapt resource value: 0x7f080018
			public const int imgbatteryindicator = 2131230744;
			
			// aapt resource value: 0x7f080004
			public const int llCH1 = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int llCH1helper = 2131230721;
			
			// aapt resource value: 0x7f08001d
			public const int llCH2 = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int llCH2helper = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int rlActivity = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int rlHelperMarkerMeasurement1 = 2131230735;
			
			// aapt resource value: 0x7f080028
			public const int rlHelperMarkerMeasurement2 = 2131230760;
			
			// aapt resource value: 0x7f080013
			public const int rlHelperMeasurement1 = 2131230739;
			
			// aapt resource value: 0x7f08002c
			public const int rlHelperMeasurement2 = 2131230764;
			
			// aapt resource value: 0x7f080017
			public const int rlbattery = 2131230743;
			
			// aapt resource value: 0x7f08001e
			public const int rlsettings = 2131230750;
			
			// aapt resource value: 0x7f08001a
			public const int rltriggerlayout = 2131230746;
			
			// aapt resource value: 0x7f080003
			public const int seperatorV1 = 2131230723;
			
			// aapt resource value: 0x7f08003f
			public const int seperatorV10 = 2131230783;
			
			// aapt resource value: 0x7f080041
			public const int seperatorV11 = 2131230785;
			
			// aapt resource value: 0x7f080005
			public const int seperatorV12 = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int seperatorV2 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int seperatorV3 = 2131230731;
			
			// aapt resource value: 0x7f08003b
			public const int seperatorV5 = 2131230779;
			
			// aapt resource value: 0x7f080031
			public const int seperatorV6 = 2131230769;
			
			// aapt resource value: 0x7f080022
			public const int seperatorV7 = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int seperatorV8 = 2131230756;
			
			// aapt resource value: 0x7f08001c
			public const int seperatorV9 = 2131230748;
			
			// aapt resource value: 0x7f080012
			public const int spMarkerMeasurement1 = 2131230738;
			
			// aapt resource value: 0x7f08002b
			public const int spMarkerMeasurement2 = 2131230763;
			
			// aapt resource value: 0x7f080016
			public const int spMeasurement1 = 2131230742;
			
			// aapt resource value: 0x7f08002f
			public const int spMeasurement2 = 2131230767;
			
			// aapt resource value: 0x7f080010
			public const int txtMarkerMeasurement1 = 2131230736;
			
			// aapt resource value: 0x7f080029
			public const int txtMarkerMeasurement2 = 2131230761;
			
			// aapt resource value: 0x7f080014
			public const int txtMeasurement1 = 2131230740;
			
			// aapt resource value: 0x7f08002d
			public const int txtMeasurement2 = 2131230765;
			
			// aapt resource value: 0x7f08003c
			public const int txtTimebase = 2131230780;
			
			// aapt resource value: 0x7f080032
			public const int txtTrigger = 2131230770;
			
			// aapt resource value: 0x7f08000d
			public const int txtVDIV1 = 2131230733;
			
			// aapt resource value: 0x7f080026
			public const int txtVDIV2 = 2131230758;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int AC = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ACbold = 2131099658;
			
			// aapt resource value: 0x7f06001f
			public const int Calibrating = 2131099679;
			
			// aapt resource value: 0x7f06000b
			public const int DC = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int DCbold = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int GND = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int GNDbold = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f06001d
			public const int autorange = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int battery = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int channel1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int channel1bold = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int channel1boldfull = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int channel1full = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int channel2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int channel2bold = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int channel2boldfull = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int channel2full = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int hold = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int holdbold = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int normal = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int normalbold = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int once = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int oncebold = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int placeholder = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int probe = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int run = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int runbold = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int seperator = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int timebase = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int trigger = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int voltime = 2131099678;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
